services:
  cinecasal:
    build: .
    container_name: cinecasal
    restart: unless-stopped
    env_file: .env
    networks:
      - root_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cinecasal.rule=Host(`cinecasal.simpletechdata.cloud`)"
      - "traefik.http.routers.cinecasal.tls=true"
      - "traefik.http.routers.cinecasal.entrypoints=web,websecure"
      - "traefik.http.routers.cinecasal.tls.certresolver=mytlschallenge"
      - "traefik.http.services.cinecasal.loadbalancer.server.port=3000"

networks:
  root_default:
    external: true
