services:
  cinecasal:
    build: .
    container_name: cinecasal
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cinecasal.rule=Host(`cinecasal.simpletechdata.cloud`)"
      - "traefik.http.routers.cinecasal.entrypoints=websecure"
      - "traefik.http.routers.cinecasal.tls.certresolver=letsencrypt"
      - "traefik.http.services.cinecasal.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
